version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFAKA_CREATE_TOPICS: "web:1:1,ntp:1:1,dns:1:1,worker:1:1:other:1:1,firewall:1:1"
      KAFKA_ADVERTISED_HOST_NAME: 10.241.80.51
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  firewall_processor:
    image: willnx/vlab-firewall-processor
    restart: unless-stopped
    environment:
      - INFLUXDB_SERVER=vlab-data.emc.com
      - INFLUXDB_USER=vlabAdmin
      - INFLUXDB_PASSWD_FILE=/influx_creds.txt
      - CIPHER_KEY_FILE=/log_sender.key
      - KAFKA_SERVER=10.241.80.51:9092
      - KAFKA_TOPIC=firewall
    volumes:
      - /etc/vlab/influx_creds.txt:/influx_creds.txt:ro
      - /etc/vlab/log_sender.key:/log_sender.key:ro

  weblog_processor:
    image: willnx/vlab-weblog-processor
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_SERVER=10.241.80.50
      - ELASTICSEARCH_USER=vlabAdmin
      - ELASTICSEARCH_DOC_TYPE=web
      - ELASTICSEARCH_PASSWD_FILE=/es_creds.txt
      - CIPHER_KEY_FILE=/log_sender.key
      - KAFKA_SERVER=10.241.80.51:9092
      - KAFKA_TOPIC=web
    volumes:
      - /etc/vlab/es_creds.txt:/es_creds.txt:ro
      - /etc/vlab/log_sender.key:/log_sender.key:ro

  workerlog_processor:
    image: willnx/vlab-workerlog-processor
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_SERVER=10.241.80.50
      - ELASTICSEARCH_USER=vlabAdmin
      - ELASTICSEARCH_DOC_TYPE=worker
      - ELASTICSEARCH_PASSWD_FILE=/es_creds.txt
      - CIPHER_KEY_FILE=/log_sender.key
      - KAFKA_SERVER=10.241.80.51:9092
      - KAFKA_TOPIC=worker
    volumes:
      - /etc/vlab/es_creds.txt:/es_creds.txt:ro
      - /etc/vlab/log_sender.key:/log_sender.key:ro

  dnslog_processor:
    image: willnx/vlab-dnslog-processor
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_SERVER=10.241.80.50
      - ELASTICSEARCH_USER=vlabAdmin
      - ELASTICSEARCH_DOC_TYPE=dns
      - ELASTICSEARCH_PASSWD_FILE=/es_creds.txt
      - CIPHER_KEY_FILE=/log_sender.key
      - KAFKA_SERVER=10.241.80.51:9092
      - KAFKA_TOPIC=dns
    volumes:
      - /etc/vlab/es_creds.txt:/es_creds.txt:ro
      - /etc/vlab/log_sender.key:/log_sender.key:ro
